### ISSUE TITLE
部署完报错，请看一下

### ISSUE THREAD

**Issue by kvgary** [Yanyutin753/pictureChange#11]
[ERROR][2024-04-06 14:09:07][chat_channel.py:304] - Worker return exception: name 'curdir' is not defined
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wechat\channel\chat_channel.py", line 171, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wechat\channel\chat_channel.py", line 183, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wechat\plugins\plugin_manager.py", line 191, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wechat\plugins\godcmd\godcmd.py", line 403, in on_handle_context
    config_path = os.path.join(curdir, "../../config.json")
NameError: name 'curdir' is not defined

**Comment by Yanyutin753** [comment]
请重新替换一下`godcmd.py`

**Comment by Yanyutin753** [comment]
@kvgary

**Comment by kvgary** [comment]
已经重新下载替换了（个人号下面的godcmd.py），还是一样

**Comment by Yanyutin753** [comment]
什么报错

**Comment by kvgary** [comment]
如下：
[ERROR][2024-04-07 11:43:08][chat_channel.py:304] - Worker return exception: name 'curdir' is not defined
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\chatgpt-on-wechat\channel\chat_channel.py", line 171, in _handle
    reply = self._generate_reply(context)
  File "D:\chatgpt-on-wechat\channel\chat_channel.py", line 183, in _generate_reply
    e_context = PluginManager().emit_event(
  File "D:\chatgpt-on-wechat\plugins\plugin_manager.py", line 191, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "D:\chatgpt-on-wechat\plugins\godcmd\godcmd.py", line 403, in on_handle_context
    config_path = os.path.join(curdir, "../../config.json")
NameError: name 'curdir' is not defined

**Comment by Yanyutin753** [comment]
不好意思啊 哈哈哈哈 昨天改了忘记上传github了

**Comment by Yanyutin753** [comment]
重新改一下这个文件估计没有问题
